name: Python Tests

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    
    - name: Run tests
      run: |
        cd python
        python -m unittest test_gilded_rose.py -v
    
    - name: Run tests with coverage
      run: |
        cd python
        coverage run -m unittest test_gilded_rose.py
        coverage report -m